[server]
host = "localhost"
port = 8080

[db]
host = "localhost"
database = "server"
user = "nano"
password = "nano_db"

[scrypt]
log_n = 11
r = 4
p = 1

[pool]
max_size = 12
connection_timeout = 30
idle_timeout = 300
max_lifetime = 1800 # 30 min

[session]
access_lifetime = 1800 # 30 min
offline_lifetime = 604800 # 7 days
